app.index:
    path: /
    defaults:
        _controller: AppBundle:Default:index
    methods: [GET]

app.page_one:
    path: /pages/one
    defaults:
        _controller: AppBundle:Pages:pageOne
    methods: [GET]

app.page_two:
    path: /pages/two
    defaults:
        _controller: AppBundle:Pages:pageTwo
    methods: [GET]